import api from './api';

const factoryPayrollService = {
  // ============================================
  // RATE MANAGEMENT
  // ============================================
  
  // Get all factory workers with their rates
  getAllWorkersWithRates: async (employeeStatus = 'ACTIVE') => {
    const response = await api.get(`/factory-payroll/workers-with-rates?employee_status=${employeeStatus}`);
    return response;
  },

  // Assign rate to a worker
  assignWorkerRate: async (employeeId, dailyRate, effectiveFrom) => {
    const response = await api.post('/factory-payroll/rates/assign', {
      employee_id: employeeId,
      daily_rate: dailyRate,
      effective_from: effectiveFrom
    });
    return response;
  },

  // Get current rate for a worker
  getWorkerCurrentRate: async (employeeId, asOfDate = null) => {
    const params = asOfDate ? { as_of_date: asOfDate } : {};
    const response = await api.get(`/factory-payroll/rates/current/${employeeId}`, { params });
    return response;
  },

  // Get rate history for a worker
  getWorkerRateHistory: async (employeeId) => {
    const response = await api.get(`/factory-payroll/rates/history/${employeeId}`);
    return response;
  },

  // Bulk assign rates — rates array includes effective_from per employee
  bulkAssignRates: async (rates) => {
    const response = await api.post('/factory-payroll/rates/bulk-assign', { rates });
    return response;
  },

  // Download rate upload template (generated by backend with styling)
  downloadRateTemplate: async () => {
    const token = localStorage.getItem('hrms_token');
    const companyCode = import.meta.env.VITE_COMPANY_CODE;
    const currentView = localStorage.getItem('preferred_view') || 'HR';
    const headers = {
      'Authorization': `Bearer ${token}`,
      'X-Current-View': currentView,
    };
    if (companyCode) headers['X-Company-Code'] = companyCode;

    const response = await fetch(`${api.baseURL}/factory-payroll/rates/template`, { headers });
    if (!response.ok) throw new Error('Failed to download template');

    const blob = await response.blob();
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `factory_rate_template_${new Date().toISOString().split('T')[0]}.xlsx`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    window.URL.revokeObjectURL(url);
  },

  // Get rate statistics
  getRateStatistics: async () => {
    const response = await api.get('/factory-payroll/rates/statistics');
    return response;
  },

  // ============================================
  // PAYROLL CONFIGURATION
  // ============================================
  
  // Get payroll configuration
  getPayrollConfig: async () => {
    const response = await api.get('/factory-payroll/config');
    return response;
  },

  // Update payroll configuration
  updatePayrollConfig: async (config) => {
    const response = await api.put('/factory-payroll/config', config);
    return response;
  },

  // ============================================
  // PAYROLL PERIODS
  // ============================================
  
  // Get all payroll periods
  getPayrollPeriods: async () => {
    const response = await api.get('/factory-payroll/periods');
    return response;
  },

  // Create new payroll period
  createPayrollPeriod: async (year, month) => {
    const response = await api.post('/factory-payroll/periods', {
      year,
      month
    });
    return response;
  },

  // ============================================
  // PAYROLL CALCULATION
  // ============================================
  
  // Calculate payroll for a period
  calculatePayroll: async (periodId) => {
    const response = await api.post('/factory-payroll/calculate', {
      period_id: periodId
    });
    return response;
  },

  // Get payroll summary for a period
  getPayrollSummary: async (periodId) => {
    const response = await api.get(`/factory-payroll/summary/${periodId}`);
    return response;
  },

  // Lock payroll period
  lockPayrollPeriod: async (periodId) => {
    const response = await api.post('/factory-payroll/lock', { period_id: periodId });
    return response;
  },

  unlockPayrollPeriod: async (periodId) => {
    const response = await api.post('/factory-payroll/unlock', { period_id: periodId });
    return response;
  },

  deletePayrollPeriod: async (periodId) => {
    const response = await api.delete(`/factory-payroll/periods/${periodId}`);
    return response;
  },
};

export default factoryPayrollService;
